[package]
name = "citycam"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
regex = "1.11.1"
image = "0.24.9"
tempfile = "3.18.0"
chrono = "0.4.40"
rand = "0.8.5"
rand_distr = "0.4.3"
anyhow = "1.0.97"

